services:
  pg:
    image: postgres:16
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=orders
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders -d orders"]
      interval: 5s
      timeout: 3s
      retries: 30
volumes: { pg_data: {} }